apiVersion: apps/v1
kind: Deployment
metadata:
  name: life-form
spec:
  selector:
    matchLabels:
      app: life-form
  replicas: 4
  template:
    metadata:
      labels:
        app: life-form
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.14.2
        ports:
        - containerPort: 80
